### ISSUE TITLE
Roadmap: Release 0.4.0

### ISSUE THREAD

**Issue by memmett** [Parallel-in-Time/PFASST#151]
I think we're getting close to being able to release 0.4.0.

Blockers
- [x] #31 (see #150) - LU decomp
- [x] #127 - iteration control for Boris
- [x] #84 - split up decls/impls
- [x] #173 - getting it up&running on JUQUEEN/JUDGE
- [x] #166 - logging with parallel builds
- [x] #174 - bug with time step distribution among MPI ranks
- [x] #180 - Boris-PFASST

Punters
- [x] #79 - profilers
- [x] #75 - testing Q vs nodes
- [x] #70 - convergence tests for MLSDC and PFASST
- [x] #19 - mat_apply (should this be closed?)

Thoughts?  Please move things around if you'd like!

After 0.4.0 I think we should consider a 1.0.0 release.

**Comment by torbjoernk** [comment]
Thanks for bringing this up, @memmett.

I'll try to tackle #127 and #84 this week.

#19 can be closed and forgotten about for now I think.

I'd like to add another point, which I hope to also tackle this week: Testing PFASST++ on our "little toy machines" JUQUEEN and JUDGE. I'd love to have it up and running for v0.4.0.

Updating above list.

**Comment by torbjoernk** [comment]
I guess, it's time for wrapping up. Once I've tested the Boris-PFASST stuff more thoroughly (it works! :fireworks:) I'll create the release branch by end of the week. So we can get the v0.4.0 release out by end of the month without a big hazel.

**Comment by memmett** [comment]
Sounds good.  I will get that LU decomp thinger going... also, I found my GPG keys.  Yay.

**Comment by memmett** [comment]
LU decomp seems to be working.  Will wait until Jenkins is happy before checking that one off.  Going to push all the 'punters' off to 1.0.

**Comment by torbjoernk** [comment]
I've just created the release branch. Going to tweak Jenkins a bit to hopefully behave a little better. :expressionless: 

Now it's time for a few documentation and cleanup PRs :smiley: 

Plus the Boris-PFASST. Or should we postpone this to v1.0.0? Although 1.0.0 was not intended for new features.

**Comment by torbjoernk** [comment]
Little update: I've served Jenkins some :cake: and now he is building the development branch in less than 5 minutes compared to 20 before. Still in all combinations (`{gcc,clang,mpi}/{Debug,Release}`). [ccache](https://ccache.samba.org/) :+1:

**Comment by torbjoernk** [comment]
I'm going to tag the first release candidate once #184 and #185 are merged. While doing that I'll prepare the changelog.

Any further points you guys want to see in v0.4.0? I think I'll do the release next week.

**Comment by torbjoernk** [comment]
The release is out. Now let's concentrate on polishing up the code base for the first milestone release.
